image: node:20

pages:
  stage: deploy
  script:
    # Instalamos pnpm en el servidor de GitLab
    - npm install -g pnpm
    # Instalamos tus dependencias
    - pnpm install
    # Construimos la versión de producción de la interfaz
    - pnpm run build
    # Vite guarda el resultado en la carpeta 'dist', pero GitLab Pages exige que se llame 'public'. Así que la renombramos:
    - rm -rf public
    - mv dist public
  artifacts:
    paths:
      - public
  rules:
    # Esto asegura que solo se publique cuando subas cambios a tu rama principal (verifica si tu rama se llama 'main' o 'master')
    - if: $CI_COMMIT_BRANCH == "main"